// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xclobqpljuazmpqsrgaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbG9icXBsanVhem1wcXNyZ2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MzI2NTYsImV4cCI6MjA1NjAwODY1Nn0.jb0X-6raSKojpHlJuK4nHzmSfExzKMS6RzeO4bbbpxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);